name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          VERSION=$(npm view @minecraft/server version)
          echo "module version: $VERSION"
