name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest stable version
        run: |
          VERSION=$(npm show @minecraft/server versions --json | jq -r '
            map(select(test("^(?!.*preview)"))) | .[-1] |
            try match(".*(-beta)").string // .
          ')
          echo "Latest stable module version: $VERSION"
